// Archivo de productos de prueba para desarrollo
import type { Product } from '../types';

export const mockProducts: Product[] = [
    {
        id: '1',
        title: 'Remera básica',
        description: 'Remera de algodón 100% orgánico',
        price: 19.99,
        images: ['https://placehold.co/300x300', 'https://placehold.co/300x300', 'https://placehold.co/300x300', 'https://placehold.co/300x300'],
        categoryName: 'Ropa',
        stock: 10,
        rating: 4.5,
        sku: 'SKU-001',
        brand: 'Marca Ejemplo',
        isActive: true,
        createdAt: '2025-05-24T00:00:00Z',
        updatedAt: '2025-05-24T00:00:00Z',
        sizes: ['S', 'M', 'L'],
        colors: ['Rojo', 'Azul', 'Negro'],
    },
    {
        id: '2',
        title: 'Pantalón de mezclilla',
        description: 'Pantalón cómodo y resistente',
        price: 39.99,
        images: ['https://placehold.co/300x300'],
        categoryName: 'Ropa',
        stock: 20,
        rating: 4.7,
        sku: 'SKU-002',
        brand: 'Marca Ejemplo',
        isActive: true,
        createdAt: '2025-05-24T00:00:00Z',
        updatedAt: '2025-05-24T00:00:00Z',
        sizes: ['M', 'L', 'XL'],
        colors: ['Negro', 'Gris'],
    },
    {
        id: '3',
        title: 'Zapatillas deportivas',
        description: 'Zapatillas cómodas para el día a día',
        price: 59.99,
        images: ['https://placehold.co/300x300'],
        categoryName: 'Calzado',
        stock: 15,
        rating: 4.8,
        sku: 'SKU-003',
        brand: 'Marca Ejemplo',
        isActive: false,
        createdAt: '2025-05-24T00:00:00Z',
        updatedAt: '2025-05-24T00:00:00Z',
        sizes: ['M', 'L', 'XL'],
        colors: ['Blanco', 'Negro'],
    },
    {
        id: '4',
        title: 'Botines de cuero',
        description: 'Botines elegantes para ocasiones especiales',
        price: 89.99,
        images: ['https://placehold.co/300x300'],
        categoryName: 'Calzado',
        stock: 8,
        rating: 4.6,
        sku: 'SKU-004',
        brand: 'Marca Ejemplo',
        isActive: false,
        createdAt: '2025-05-24T00:00:00Z',
        updatedAt: '2025-05-24T00:00:00Z',
        sizes: ['M', 'L'],
        colors: ['Marrón', 'Negro'],
    },
    {
        id: '5',
        title: 'Camisa de cuadros',
        description: 'Camisa de algodón con estampado de cuadros',
        price: 49.99,
        images: ['https://placehold.co/300x300'],
        categoryName: 'Ropa',
        stock: 12,
        rating: 4.4,
        sku: 'SKU-005',
        brand: 'Marca Ejemplo',
        isActive: true,
        createdAt: '2025-05-24T00:00:00Z',
        updatedAt: '2025-05-24T00:00:00Z',
        sizes: ['S', 'M', 'L'],
        colors: ['Rojo', 'Verde', 'Azul'],
    },
    {
        id: '6',
        title: 'Chaqueta de cuero',
        description: 'Chaqueta de cuero genuino',
        price: 149.99,
        images: ['https://placehold.co/300x300'],
        categoryName: 'Ropa',
        stock: 5,
        rating: 4.9,
        sku: 'SKU-006',
        brand: 'Marca Ejemplo',
        isActive: true,
        createdAt: '2025-05-24T00:00:00Z',
        updatedAt: '2025-05-24T00:00:00Z',
        sizes: ['S', 'M', 'L'],
        colors: ['Negro'],
    }
];
