import type { User } from '../types';

export const mockUsers: User[] = [
    {
        id: '1',
        name: 'Juan Pérez',
        email: 'juan.perez@email.com',
        role: 'user',
        createdAt: '2023-01-10',
        updatedAt: '2023-12-15',
        address: 'Calle Mayor 123, Madrid, 28001, España',
        phone: '+34 612 345 678',
        isActive: true,
        orders: [
            {
                id: 'ORD-001',
                userId: '1',
                items: [],
                total: 89.99,
                status: 'delivered',
                createdAt: '2023-12-15',
                updatedAt: '2023-12-15',
                shippingAddress: 'Calle Mayor 123, Madrid, 28001, España',
            },
            {
                id: 'ORD-002',
                userId: '1',
                items: [],
                total: 45.5,
                status: 'delivered',
                createdAt: '2023-12-10',
                updatedAt: '2023-12-10',
                shippingAddress: 'Calle Mayor 123, Madrid, 28001, España',
            },
            {
                id: 'ORD-003',
                userId: '1',
                items: [],
                total: 129.99,
                status: 'shipped',
                createdAt: '2023-12-05',
                updatedAt: '2023-12-05',
                shippingAddress: 'Calle Mayor 123, Madrid, 28001, España',
            },
        ],
    },
    {
        id: '2',
        name: 'Ana García',
        email: 'ana.garcia@email.com',
        role: 'admin',
        createdAt: '2022-05-20',
        updatedAt: '2023-11-30',
        address: 'Calle Gran Vía 45, Barcelona, 08010, España',
        phone: '+34 678 901 234',
        isActive: true,
        orders: [],
    },
];
